import 'package:flutter/material.dart';
import '../widgets/cartao_objeto.dart';
import 'tela_comprovante.dart';
class TelaCadastroObjeto extends StatefulWidget { const TelaCadastroObjeto({super.key}); @override State<TelaCadastroObjeto> createState()=>_TelaCadastroObjetoState(); }
class _TelaCadastroObjetoState extends State<TelaCadastroObjeto> {
 final nome=TextEditingController(), local=TextEditingController(); int total=0; String? ultimoNome, ultimoLocal; bool devolvido=false;
 void registrar(){ if(nome.text.trim().isEmpty||local.text.trim().isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Preencha todas as informações.')));return;} setState((){total++;ultimoNome=nome.text.trim();ultimoLocal=local.text.trim();devolvido=false;}); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Objeto registrado com sucesso!'))); nome.clear();local.clear(); }
 void comprovante(){if(ultimoNome==null){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Registre um objeto antes de abrir o comprovante.')));return;} Navigator.push(context,MaterialPageRoute(builder:(_)=>TelaComprovante(nome:ultimoNome!,local:ultimoLocal!,situacao:devolvido?'Objeto devolvido':'Aguardando retirada',total:total)));}
 @override void dispose(){nome.dispose();local.dispose();super.dispose();}
 @override Widget build(BuildContext context){final grande=MediaQuery.sizeOf(context).width>=600; return Scaffold(appBar:AppBar(title:const Text('Achados e Perdidos')),body:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Column(children:[TextField(controller:nome,decoration:const InputDecoration(labelText:'Nome do objeto',border:OutlineInputBorder(),prefixIcon:Icon(Icons.inventory_2))),const SizedBox(height:12),TextField(controller:local,decoration:const InputDecoration(labelText:'Local onde foi encontrado',border:OutlineInputBorder(),prefixIcon:Icon(Icons.location_on))),const SizedBox(height:16),Row(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.find_in_page,size:60),const SizedBox(width:20),Text('Registros: $total',style:const TextStyle(fontSize:22))]),const SizedBox(height:16),FilledButton.icon(onPressed:registrar,icon:const Icon(Icons.add),label:const Text('Registrar objeto')),const SizedBox(height:20),if(ultimoNome!=null)LayoutBuilder(builder:(context,c)=>grande?ConstrainedBox(constraints:const BoxConstraints(maxWidth:650),child:_card()):_card()),const SizedBox(height:16),OutlinedButton(onPressed:comprovante,child:const Text('Ver comprovante'))])));}
 Widget _card()=>CartaoObjeto(nome:ultimoNome!,local:ultimoLocal!,situacao:devolvido?'Objeto devolvido':'Aguardando retirada',cor:devolvido?Colors.green.shade100:Colors.orange.shade100,onPressed:()=>setState(()=>devolvido=!devolvido));
}
