// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF2GR15dZwzgaVoOv0krT1Vap6Tj-V1Qg',
    appId: '1:941543842430:web:e9f503dbf435d019196e2f',
    messagingSenderId: '941543842430',
    projectId: 'flutterqueijo',
    authDomain: 'flutterqueijo.firebaseapp.com',
    storageBucket: 'flutterqueijo.firebasestorage.app',
    measurementId: 'G-DYMVSLYMDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCjqerWp8-JIVdpD21K6kCOtCE6OXpc4',
    appId: '1:941543842430:android:10bfeb988d596a20196e2f',
    messagingSenderId: '941543842430',
    projectId: 'flutterqueijo',
    storageBucket: 'flutterqueijo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrNlWU1V1nleayp9rbqUKFNT3xluVUQwM',
    appId: '1:941543842430:ios:f2a8487e0bf5d45a196e2f',
    messagingSenderId: '941543842430',
    projectId: 'flutterqueijo',
    storageBucket: 'flutterqueijo.firebasestorage.app',
    iosBundleId: 'com.example.atividadeEstoque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrNlWU1V1nleayp9rbqUKFNT3xluVUQwM',
    appId: '1:941543842430:ios:f2a8487e0bf5d45a196e2f',
    messagingSenderId: '941543842430',
    projectId: 'flutterqueijo',
    storageBucket: 'flutterqueijo.firebasestorage.app',
    iosBundleId: 'com.example.atividadeEstoque',
  );
}
