// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoy5T3fcJoNJx77g0m_JCJsP4G537Psww',
    appId: '1:306914949007:web:4978241d5d8e743a8c3dfa',
    messagingSenderId: '306914949007',
    projectId: 'centraldemissoes-f460c',
    authDomain: 'centraldemissoes-f460c.firebaseapp.com',
    storageBucket: 'centraldemissoes-f460c.firebasestorage.app',
    measurementId: 'G-1T410G092R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZgbMrKgoLdHN8jgVKvhWbI_spTgQu9M',
    appId: '1:306914949007:android:d7fd99c769e2bf288c3dfa',
    messagingSenderId: '306914949007',
    projectId: 'centraldemissoes-f460c',
    storageBucket: 'centraldemissoes-f460c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtcJyEoNLfuFYhbex218FUlNiRXBtazBk',
    appId: '1:306914949007:ios:d75cb3e4783383028c3dfa',
    messagingSenderId: '306914949007',
    projectId: 'centraldemissoes-f460c',
    storageBucket: 'centraldemissoes-f460c.firebasestorage.app',
    iosBundleId: 'com.example.atividadeEstoque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtcJyEoNLfuFYhbex218FUlNiRXBtazBk',
    appId: '1:306914949007:ios:d75cb3e4783383028c3dfa',
    messagingSenderId: '306914949007',
    projectId: 'centraldemissoes-f460c',
    storageBucket: 'centraldemissoes-f460c.firebasestorage.app',
    iosBundleId: 'com.example.atividadeEstoque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoy5T3fcJoNJx77g0m_JCJsP4G537Psww',
    appId: '1:306914949007:web:31e5e475926b0e6b8c3dfa',
    messagingSenderId: '306914949007',
    projectId: 'centraldemissoes-f460c',
    authDomain: 'centraldemissoes-f460c.firebaseapp.com',
    storageBucket: 'centraldemissoes-f460c.firebasestorage.app',
    measurementId: 'G-QD197Y82DE',
  );
}
