import 'package:flutter/material.dart';
import 'tela_diagnostico.dart';
import '../widgets/cartao_peca.dart';
class TelaOficina extends StatefulWidget{const TelaOficina({super.key});@override State<TelaOficina> createState()=>_TelaOficinaState();}
class _TelaOficinaState extends State<TelaOficina>{final nome=TextEditingController();int energia=30;final pecas=[false,false,false];String resultado='Nenhum teste realizado.';bool mostrarResultado=false;
 String situacao(int i)=>pecas[i]?'Instalada':'Não instalada';
 void energiaAlterar(int v)=>setState(()=>energia=(energia+v).clamp(0,100));
 void testar(){if(nome.text.trim().isEmpty){_erro('Informe o nome do robô.');return;}if(energia<50){_erro('Energia insuficiente para realizar o teste.');return;}if(pecas.where((p)=>p).length<2){_erro('Instale pelo menos duas peças.');return;}setState(() { resultado='Teste realizado com sucesso!'; mostrarResultado=true; });}
 void _erro(String msg){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(msg)));}
 void diagnostico(){Navigator.push(context,MaterialPageRoute(builder:(_)=>TelaDiagnostico(nome:nome.text.trim().isEmpty?'Não informado':nome.text.trim(),energia:energia,instaladas:pecas.where((p)=>p).length,resultado:resultado)));}
 @override void dispose(){nome.dispose();super.dispose();}
 @override Widget build(BuildContext context){final grande=MediaQuery.sizeOf(context).width>=700;final cards=[CartaoPeca(icone:Icons.face,nome:'Cabeça',situacao:situacao(0),instalada:pecas[0],onPressed:()=>setState(()=>pecas[0]=!pecas[0])),CartaoPeca(icone:Icons.precision_manufacturing,nome:'Braço mecânico',situacao:situacao(1),instalada:pecas[1],onPressed:()=>setState(()=>pecas[1]=!pecas[1])),CartaoPeca(icone:Icons.sensors,nome:'Sensor',situacao:situacao(2),instalada:pecas[2],onPressed:()=>setState(()=>pecas[2]=!pecas[2]))];return Scaffold(appBar:AppBar(title:const Text('Oficina de Robôs')),body:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Column(children:[TextField(controller:nome,decoration:const InputDecoration(labelText:'Nome do robô',border:OutlineInputBorder(),prefixIcon:Icon(Icons.edit))),const SizedBox(height:16),const Icon(Icons.smart_toy,size:90),const SizedBox(height:12),_painelEnergia(),const SizedBox(height:12),Wrap(spacing:12,children:[FilledButton.icon(onPressed:()=>energiaAlterar(-10),icon:const Icon(Icons.remove),label:const Text('Remover energia')),FilledButton.icon(onPressed:()=>energiaAlterar(10),icon:const Icon(Icons.add),label:const Text('Adicionar energia'))]),const SizedBox(height:20),LayoutBuilder(builder:(context,c)=>grande?Row(children:cards.map((x)=>Expanded(child:Padding(padding:const EdgeInsets.all(5),child:x))).toList()):Column(children:cards)),const SizedBox(height:15),Text('Peças instaladas: ${pecas.where((p)=>p).length}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),FilledButton(onPressed:testar,child:const Text('Testar robô')),const SizedBox(height:12),AnimatedOpacity(opacity:mostrarResultado?1:0,duration:const Duration(milliseconds:500),child:Text(resultado,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold),textAlign:TextAlign.center)),const SizedBox(height:12),OutlinedButton(onPressed:diagnostico,child:const Text('Abrir diagnóstico'))])));}
 Widget _painelEnergia(){Color cor=energia<50?Colors.red.shade100:energia<=70?Colors.orange.shade100:Colors.green.shade100;return AnimatedContainer(duration:const Duration(milliseconds:350),padding:const EdgeInsets.all(20),width:double.infinity,decoration:BoxDecoration(color:cor,borderRadius:BorderRadius.circular(18)),child:Column(children:[const Text('Nível atual de energia'),Text('$energia%',style:const TextStyle(fontSize:40,fontWeight:FontWeight.bold))]));}
}
